# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbcmc',
                'doc_host': 'https://ymoisan.github.io',
                'git_url': 'https://github.com/ymoisan/nbcmc',
                'lib_path': 'nbcmc'},
  'syms': {'nbcmc.core': {'nbcmc.core.foo': ('core.html#foo', 'nbcmc/core.py')}}}
